### ISSUE TITLE
Workflow not working (Alfred 5 / WF 2.0.7)

### ISSUE THREAD

**Issue by daemuu** [westerlind/alfred-raindrop-search#19] opened 2022-10-22 12:25 UTC
Hey @westerlind,

In complement to my [post in the Alfred forum](https://www.alfredforum.com/topic/14357-search-and-add-bookmarks-to-raindropio/?do=findComment&comment=99879), i drop an issue here as well.

Recently, i remembered that i have this amazing Raindrop Alfred workflow on my computer, and i wanted to have a new try with it, but i experienced some errors in the trials.

Below is what comes from the Alfred Workflow debugging console when i try to search with the term "design" as an example : would you have any clues on what is (not) going on please ?

Thanks a lot, & have a good one,
D. 

---

[14:06:57.630] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[14:06:58.760] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[14:06:58.763] STDERR: Search Raindrop.io[Script Filter] 🍺
14:06:57 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
14:06:58 feedback.go:509: Sent 2 result(s) to Alfred
14:06:58 workflow.go:405: ------------------ 772.29906ms -------------------
[14:06:58.764] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "N5A3RSYU0AT4REF85O0SAC46"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}
[14:07:08.769] Search Raindrop.io[Script Filter] Queuing argument 'design'
[14:07:10.150] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[14:07:10.155] STDERR: Search Raindrop.io[Script Filter] 🍺
14:07:09 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
14:07:10 feedback.go:509: Sent 0 result(s) to Alfred
14:07:10 workflow.go:405: ------------------ 1.031134258s ------------------
[14:07:10.156] Search Raindrop.io[Script Filter] /**** Unexpected response from server ****
Bad Request
***********************************/

/**** Unexpected response from server ****
Bad Request
***********************************/

{
  "variables": {
    "AW_SESSION_ID": "N5A3RSYU0AT4REF85O0SAC46"
  },
  "items": null
}
[14:07:10.157] ERROR: Search Raindrop.io[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
/**** Unexpected response from server ****
Bad Request
***********************************/

/**** Unexpected response from server ****
Bad Request
***********************************/

{
  "variables": {
    "AW_SESSION_ID": "N5A3RSYU0AT4REF85O0SAC46"
  },
  "items": null
}

**Comment by westerlind** [comment] 2022-10-22 16:25
Hi @woodoxherd 

I don't know for sure what the problem is, but one possibility is that the authentication ended up with some type of issue as a consequense of the workflow being used before, but not for a long time.

You could try to force a re-authentication by opening the Keychain Access app, searching for "raindrop" there, and remove the raindrop-search object from there.
After doing that you should get to log in again when you use the workflow the next time, and hopefully that will fix the issue and make everything work from now on.

**Comment by daemuu** [comment] 2022-10-22 16:38
Hi Andreas @westerlind  and thanks very much for your celerity !
I did the forced re-authentification and now everything is working like a charm ! 🙏

BTW, and maybe before to close this issue : is there a way to display bookmarks first rather than collections, by any chances ?

Have a very good One,
D.

**Comment by westerlind** [comment] 2022-10-22 16:48
@woodoxherd Glad to hear that it helped!

There is no way of changing that at the moment, but it is a good suggestion so I will look into adding support for changing that.

Would it be a good solution for you if I simply give an option for letting Alfred decide the order of the results based on what it thinks is the most relevant, or what you are searching for the most, rather than simply changing the order of bookmarks/collections/tags?

The current behaviour is that Raindrop decides the order of the bookmarks, and as it can not send the tags and collections together with the bookmarks, I needed to put them separate from the bookmarks, so I simply put them first instead as it seemed more likely that you might want to find a collection or tag with the name you searched for rather than a bookmark, and there would likely not be as many collections and tags, so the bookmarks should show up somewhat high up in the list anyway.

**Comment by westerlind** [comment] 2022-10-22 16:52
I closed the issue by mistake, so it's opened again 🙂 

I will close it for real when I think we have a conclusion about the order of bookmarks/tags/collections and how that can be made better.

**Comment by daemuu** [comment] 2022-10-23 09:07
Hey Andreas @westerlind,

Well, to me, as you have already implemented a searchable "Browse your Raindrop.io **collections**" it does not really make sense to have the collections happening again into the "Search your Raindrop.io **bookmarks**" main feature (tags at first place would be ok though). Then :

It could be one solution to let Alfred priorize based on one' use.

It could be also a solution, if technically feasible, to also create as well a kind of searchable "Browse your Raindrop.io tags" and just let the only actual bookmarks populate the main "Search your Raindrop.io **bookmarks**" ?

Finally It could also be another solution to crafts triggers in a other way, instead or in complement to general "r" trigger :
- "rb" for bookmarks search only (without tags and collections)
- "rc" for collections search only (as is your searchable "Browse your Raindrop.io collections")
- "rt" for tags search only (as would be the searchable "Browse your Raindrop.io tags")

(In the same spirit than [here](https://github.com/mpco/AlfredWorkflow-Calibre-Search), for a Calibre Search Alfred Workflow)

And if i could choose an order into this "r" general trigger, it would be bookmarks/collections/tags (or bookmark/tags/collections)

How does this sounds to you ?

**Comment by ghurth** [comment] 2022-10-26 08:27
Hello, I couldn't delete the application password.

https://user-images.githubusercontent.com/99127830/197974809-80e63aaf-e921-46da-9a00-15e969e13c2f.mp4
 
I tried a few hours after. It works!

Thank you!
Best regards, 

Geoffrey

**Comment by westerlind** [comment] 2022-10-30 17:15
@ghurth That seems really strange. There should not be any probelm to delete the password the way you tried to do, and it has always worked for me.

One thing I have noticed sometimes is that changes you do in Keychain Access (generally) is not reflected until you update the search, by for example removing or adding a letter in the search box.
Could it be the case that the credentials where actually removed, but that it simply wasn't shown in the application right away?

**Comment by ghurth** [comment] 2023-05-21 20:58
Hello, 

Sorry I am back again with the same problem. 

DEBUGGER : 

[22:49:01.699] Logging Started...
[22:49:03.546] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[22:49:04.031] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:49:04.037] STDERR: Search Raindrop.io[Script Filter] 🍺
22:49:03 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:49:04 feedback.go:509: Sent 2 result(s) to Alfred
22:49:04 workflow.go:405: ------------------ 428.150917ms ------------------
[22:49:04.041] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "DQHUJSP6MV94HLK8KHD38P0R"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}
[22:49:13.672] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[22:49:13.807] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:49:13.816] STDERR: Search Raindrop.io[Script Filter] 🍺
22:49:13 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:49:13 feedback.go:509: Sent 2 result(s) to Alfred
22:49:13 workflow.go:405: ------------------ 41.203334ms -------------------
[22:49:13.819] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "B5IVCX63MM34PLF9L49GQ730"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}
[22:49:14.687] Search Raindrop.io[Script Filter] Queuing argument 'test'
[22:49:15.846] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:49:15.873] STDERR: Search Raindrop.io[Script Filter] 🍺
22:49:14 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:49:15 feedback.go:509: Sent 0 result(s) to Alfred
22:49:15 workflow.go:405: ------------------ 1.130986542s ------------------
[22:49:15.876] Search Raindrop.io[Script Filter] /**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/


/**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/

{
  "variables": {
    "AW_SESSION_ID": "B5IVCX63MM34PLF9L49GQ730"
  },
  "items": null
}
[22:49:15.878] ERROR: Search Raindrop.io[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
/**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/


/**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/

{
  "variables": {
    "AW_SESSION_ID": "B5IVCX63MM34PLF9L49GQ730"
  },
  "items": null
}
[22:55:20.277] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[22:55:20.363] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:55:20.371] STDERR: Search Raindrop.io[Script Filter] 🍺
22:55:20 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:55:20 feedback.go:509: Sent 1 result(s) to Alfred
22:55:20 workflow.go:405: ------------------ 34.720125ms -------------------
[22:55:20.375] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "0BWMAFH7DNLUMNV33R3X7GN9"
  },
  "items": [
    {
      "title": "You are not authenticated with Raindrop.io",
      "subtitle": "Press enter to authenticate now",
      "arg": "https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038\u0026client_id=5e46fab9b2fbaee7314687d8",
      "valid": true
    }
  ]
}
[22:55:21.657] Search Raindrop.io[Script Filter] Processing complete
[22:55:21.668] Search Raindrop.io[Script Filter] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Conditional
[22:55:21.671] Search Raindrop.io[Conditional] Processing complete
[22:55:21.675] Search Raindrop.io[Conditional] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Conditional
[22:55:21.677] Search Raindrop.io[Conditional] Processing complete
[22:55:21.681] Search Raindrop.io[Conditional] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Arg and Vars
[22:55:21.684] Search Raindrop.io[Arg and Vars] Processing complete
[22:55:21.687] Search Raindrop.io[Arg and Vars] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Run Script
[22:55:22.053] Search Raindrop.io[Run Script] Processing complete
[22:55:22.065] Search Raindrop.io[Run Script] Passing output 'com.google.Chrome
' to Transform
[22:55:22.068] Search Raindrop.io[Transform] Processing complete
[22:55:22.071] Search Raindrop.io[Transform] Passing output 'com.google.Chrome' to Arg and Vars
[22:55:22.074] Search Raindrop.io[Arg and Vars] Processing complete
[22:55:22.078] Search Raindrop.io[Arg and Vars] Passing output 'com.google.Chrome' to Conditional
[22:55:22.080] Search Raindrop.io[Conditional] Processing complete
[22:55:22.082] Search Raindrop.io[Conditional] Passing output 'com.google.Chrome' to JSON Config
[22:55:22.083] Search Raindrop.io[JSON Config] Processing complete
[22:55:22.085] Search Raindrop.io[JSON Config] Passing output '' to Open URL
[22:55:29.599] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[22:55:30.043] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:55:30.054] STDERR: Search Raindrop.io[Script Filter] 🍺
22:55:29 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:55:30 feedback.go:509: Sent 2 result(s) to Alfred
22:55:30 workflow.go:405: ------------------ 409.855417ms ------------------
[22:55:30.059] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "RDSHUTX1XUG0YKGWKEIFEHDC"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}
[22:55:30.581] Search Raindrop.io[Script Filter] Queuing argument 'test'
[22:55:31.362] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:55:31.394] STDERR: Search Raindrop.io[Script Filter] 🍺
22:55:30 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:55:31 feedback.go:509: Sent 0 result(s) to Alfred
22:55:31 workflow.go:405: ------------------ 744.210667ms ------------------
[22:55:31.396] Search Raindrop.io[Script Filter] /**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/


/**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/

{
  "variables": {
    "AW_SESSION_ID": "RDSHUTX1XUG0YKGWKEIFEHDC"
  },
  "items": null
}
[22:55:31.398] ERROR: Search Raindrop.io[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
/**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/


/**** Unexpected response from server ****
{"result":true,"items":[],"count":0,"collectionId":0}
***********************************/

{
  "variables": {
    "AW_SESSION_ID": "RDSHUTX1XUG0YKGWKEIFEHDC"
  },
  "items": null
}
[22:55:32.845] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[22:55:32.983] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[22:55:32.996] STDERR: Search Raindrop.io[Script Filter] 🍺
22:55:32 workflow.go:328: ----- Search Raindrop.io/2.0.7 (AwGo/0.27.1) -----
22:55:32 feedback.go:509: Sent 2 result(s) to Alfred
22:55:32 workflow.go:405: ------------------ 40.696917ms -------------------
[22:55:33.000] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8GSOTRWFH5OAVRUQIML65IEB"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}

I delete the key chain 
I did the reauthetification. 

But the problem persist.

could you help me ? 

Best regards,

Geoffrey

**Comment by westerlind** [comment] 2023-06-04 21:50
Version 2.0.8 is now finally out, and fixes this problem.

Sorry that it has taken a while to get this solved.

**Closed as completed by westerlind** 2023-06-04 21:50 UTC

**Comment by daemuu** [comment] 2023-08-21 10:21
Hi Andreas @westerlind !

Two days ago the Notion Search Alfred workflow (v2.0.8 & MacOS Catalina 10.15.7) seemed to work perfectly fine, but yestarday it started to behave oddly again :
- When i hit "r" on Alfred, it says "You are not authenticated with Raindrop.io"
- When i "Press enter to authenticate now", i get to an [Error Raindrop API web page](https://api.raindrop.io/v1/oauth/authorize%253Fredirect_uri%253Dhttp%25253A%25252F%25252F127.0.0.1%25253A11038%2526client_id%253D5e46fab9b2fbaee7314687d8) with this only message :
`Cannot GET /v1/oauth/authorize%3Fredirect_uri%3Dhttp%253A%252F%252F127.0.0.1%253A11038%26client_id%3D5e46fab9b2fbaee7314687d8`

I checked the Keychain, and there is no entry related to your Alfred workflow.

Would you have again any clues, please ? 
Thanks a lot and have a good One !

---

PS, Here is what i get from the debugger : 

[12:07:40.728] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[12:07:41.403] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[12:07:41.406] STDERR: Search Raindrop.io[Script Filter] 🍺
12:07:41 workflow.go:328: ----- Search Raindrop.io/2.0.8 (AwGo/0.27.1) -----
12:07:41 feedback.go:509: Sent 1 result(s) to Alfred
12:07:41 workflow.go:405: ------------------ 177.293731ms ------------------
[12:07:41.407] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "9W47KS6ZZTZWI16M1RKFEXVU"
  },
  "items": [
    {
      "title": "You are not authenticated with Raindrop.io",
      "subtitle": "Press enter to authenticate now",
      "arg": "https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038\u0026client_id=5e46fab9b2fbaee7314687d8",
      "valid": true
    }
  ]
}
[12:07:44.269] Search Raindrop.io[Script Filter] Processing complete
[12:07:44.278] Search Raindrop.io[Script Filter] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Conditional
[12:07:44.279] Search Raindrop.io[Conditional] Processing complete
[12:07:44.279] Search Raindrop.io[Conditional] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Conditional
[12:07:44.280] Search Raindrop.io[Conditional] Processing complete
[12:07:44.281] Search Raindrop.io[Conditional] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Arg and Vars
[12:07:44.282] Search Raindrop.io[Arg and Vars] Processing complete
[12:07:44.282] Search Raindrop.io[Arg and Vars] Passing output 'https://raindrop.io/oauth/authorize?redirect_uri=http%3A%2F%2F127.0.0.1%3A11038&client_id=5e46fab9b2fbaee7314687d8' to Run Script
[12:07:44.725] Search Raindrop.io[Run Script] Processing complete
[12:07:44.737] Search Raindrop.io[Run Script] Passing output 'com.runningwithcrayons.Alfred-Preferences
' to Transform
[12:07:44.737] Search Raindrop.io[Transform] Processing complete
[12:07:44.738] Search Raindrop.io[Transform] Passing output 'com.runningwithcrayons.Alfred-Preferences' to Arg and Vars
[12:07:44.739] Search Raindrop.io[Arg and Vars] Processing complete
[12:07:44.740] Search Raindrop.io[Arg and Vars] Passing output 'com.runningwithcrayons.Alfred-Preferences' to Conditional
[12:07:44.742] Search Raindrop.io[Conditional] Processing complete
[12:07:44.743] Search Raindrop.io[Conditional] Passing output 'com.runningwithcrayons.Alfred-Preferences' to Arg and Vars
[12:07:44.744] Search Raindrop.io[Arg and Vars] Processing complete
[12:07:44.745] Search Raindrop.io[Arg and Vars] Passing output '' to JSON Config
[12:07:44.746] Search Raindrop.io[JSON Config] Processing complete
[12:07:44.747] Search Raindrop.io[JSON Config] Passing output '' to Open URL

**Comment by westerlind** [comment] 2023-08-22 18:15
Hi @daemuu 

I think I might know what is causing this problem, and I'm working on an update that will hopefully fix it.
The update will probably be available today or tomorrow.

**Comment by westerlind** [comment] 2023-08-22 18:49
This problem should be fixed now in version 2.0.9 which is just released a moment ago.
https://github.com/westerlind/alfred-raindrop-search/releases

**Comment by daemuu** [comment] 2023-08-23 11:58
Thank you Andreas @westerlind for your celerity : again it works like a charm now !! \°/
