### ISSUE TITLE
Adding bookmark is not working for me

### ISSUE THREAD

**Issue by ShubhamJ010** [westerlind/alfred-raindrop-search#27] opened 2023-10-09 15:03 UTC
Adding bookmark is not working for me after updating to Mac os sonoma 14

1. At first it shows up like this 
<img width="1440" alt="image" src="https://github.com/westerlind/alfred-raindrop-search/assets/40000538/f3999a59-7e19-4b84-9e07-4b97197569c3">

2. But then this disappear right away
<img width="1440" alt="image" src="https://github.com/westerlind/alfred-raindrop-search/assets/40000538/b5e4bb0b-b3fa-4c9e-853d-ba61866f56f0">

- Im using Arc browser version 1.11.0 (42160)
- MacOs sonoma (14)
- Alfred 5.1.2

**Comment by w0whitaker** [comment] 2023-10-17 12:29
I've been having the same problem in Arc (1.12.1), which is based on Chromium. I've also tried it with the Chromium app, and with Chrome, and it doesn't seem to be working in those either. Works fine in Safari.

**Comment by davidisongithub** [comment] 2023-10-17 19:14
same problem here!

**Comment by jonbstrong** [comment] 2023-10-19 20:01
Same here!

**Comment by harisonkhlil** [comment] 2023-10-21 17:48
Me too

**Comment by sysdevtra** [comment] 2023-10-22 08:52
I have the same problem and tried it in Edge and Chrome. The Alfred debug information shows the following:

[10:46:01.394] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[10:46:01.959] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[10:46:01.965] ERROR: Search Raindrop.io[Script Filter] Code 1: 6190:6353: execution error: sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file (2)

**Comment by westerlind** [comment] 2023-10-22 17:54
There does seem to be a problem with the integration with all the Chromium based browsers in Sonoma, while it still works just like before in Safari and Firefox.

I'm looking into it, and will hopefully find the cause of the issue soon.

There is a workaround that you can use by first copying the URL from the browser, then selecting any app (including the desktop) that is not a browser, and then initiate adding a bookmark.
The copied URL will then be added instead of the workflow trying to fetch anything form the browser, and that means that it can be used as a workaround until this bug is fixed.

I will try to fix this as soon as possible, but at the moment I have not been able to figure out what is causing it so I don't know how long it will actually take to come up with a fix yet.

**Comment by westerlind** [comment] 2023-10-22 18:06
Update: The problem is caused by an appearent change in how text encoding is handled in some specific situations in Sonoma.

This means that I have an idea about how to solve this, and that I should be able to have a fixed version out today or tomorrow.

**Comment by sysdevtra** [comment] 2023-10-22 21:29
Great, thank you!
This sounds very promising.

**Comment by westerlind** [comment] 2023-10-23 19:58
This problem is now fixed in version 2.0.10 which was released a minute ago.

**Closed as completed by westerlind** 2023-10-23 19:58 UTC

**Comment by w0whitaker** [comment] 2023-10-23 23:53
working for me after update. thanks for working on this!

**Comment by sysdevtra** [comment] 2023-10-24 06:03
Works for me too!
Thank you @westerlind

**Comment by ShubhamJ010** [comment] 2023-10-25 07:05
thank you so much @westerlind
