### ISSUE TITLE
this workflow cannot work in mac m1

### ISSUE THREAD

**Issue by supernihui** [westerlind/alfred-raindrop-search#8] opened 2021-05-28 22:12 UTC
I have tried many times and failed again and again. Could you help me solve this problem?

**Comment by westerlind** [comment] 2021-05-30 13:59
Hi!

Could you describe more how far you get, and what exactly happens?

I have an M1 Mac myself, and it does work for me, so I don't thing this issue is caused by that but I will try to see what I can do to help fixing your problem.

**Comment by barrymcbride** [comment] 2021-07-28 20:26
On M1 Macbook Pro
Using Chrome
OS: Monterey Beta 4

Typing "r " brings up the "Search Raindrop" command below for about 1-2 seconds and then it disappears.

**Comment by westerlind** [comment] 2021-08-03 19:25
Hi @barrymcbride

This is because Apple has removed PHP in Monterey, sadly enough, and because most of the scripting in this workflow is built on PHP, the workflow simply doesn't load.

I don't know for sure exactly what would be the best way to handle this change yet, but it seems like the solution to go for is that PHP has to be installed via for example Homebrew instead (by users of workflows like this one, that needs it), which will lead to other issues though, as Alfred itself assumes that PHP is located at /usr/bin/php (which it used to be), and that path is not even writable, so that makes the whole thing a bit tricky.

I'm working on fixing it somehow anyway! I'm on Monterey too since a few days, and don't really like this situation where I can't reach my bookmarks normally anymore.

I was thinking about rewriting this workflow in Python for a while (only some things are Python at the moment), but it turned out that Apple has deprecated that too in macOS, and will remove it in the future.

**Comment by westerlind** [comment] 2021-08-03 19:36
@supernihui Which version of macOS ar you running?
If you have not updated to the Monterey Beta, it should still work.
Have you installed the the Command Line Tools from Apple by for example running `xcode-select --install` in the terminal?
Could you try to do that in that case and see if it makes any difference? (assuming you are not running the Monterey Beta yet of course, as it will not work there at all right now)
I'm not sure it has anything to do with that, but it's possible that it does.

**Comment by westerlind** [comment] 2021-08-03 19:57
For a bit more clarity about the different things in this issue:

- The workflow does work on M1 Mac's (That's what I have been using myself since the end of 2020)
- I would still like to help with fixing the isues that @supernihui is having, but need more info about what is happening there to be able to do so.
- It does not work on Monterey though, but I have created a different issue for that now, as it has nothing to do with what this issue was created for, so that continues here: #9 
- I will close this issue in a few days if I don't get more info about the initial issue here, as I first asked about that a long time ago, and as it does actually work on M1 Macs as I said.

**Comment by westerlind** [comment] 2021-08-07 16:44
Closing this, as I have not received any more information about the initial issue.
See the previous comment for more info.

**Closed as completed by westerlind** 2021-08-07 16:44 UTC
